export const publishItems: { id: string; label: string }[] = [
  { id: "identity", label: "Identity is clear." },
  { id: "strongest-first", label: "Strongest work appears first." },
  { id: "descriptions", label: "Projects have clear descriptions." },
  { id: "roles", label: "Individual roles are identified." },
  { id: "credits", label: "Collaborators are credited." },
  { id: "videos", label: "Videos play." },
  { id: "audio", label: "Audio works." },
  { id: "mobile", label: "Mobile layout works." },
  { id: "links", label: "Links are tested." },
  { id: "contact", label: "Contact information is visible." },
  { id: "resume", label: "Résumé is current." },
  { id: "captions", label: "Captions give context." },
  { id: "placeholders", label: "No placeholder content." },
  {
    id: "courses",
    label: "Course assignments are explained for outside audiences.",
  },
  { id: "screenshots", label: "No unexplained software screenshots." },
  { id: "access", label: "Accessibility basics are covered." },
  {
    id: "status",
    label: "Projects are labeled accurately as prototypes, works in progress, or finished.",
  },
];
